---
- hosts: pi-0
  become: yes
  tasks:
    - name: Append cgroup settings
      copy:
        dest: /boot/firmware/cmdline.txt
        content: |
          console=serial0,115200 console=tty1 root=PARTUUID=7149c158-02 rootfstype=ext4 fsck.repair=yes rootwait cfg80211.ieee80211_regdom=NL cgroup_memory=1 cgroup_enable=memory
      register: boot_cmdline  

    - name: Reboot if firmware was updated
      reboot:
      when: boot_cmdline.changed

    - name: Install dependencies
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - vim
        state: present
        update_cache: yes

    - name: Disable swap
      command: swapoff -a
      ignore_errors: true

    - name: Install K3s
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik --node-external-ip=192.168.178.246" sh -
      args:
        executable: /bin/bash

    - name: Replace master server IP
      replace:
        path: /etc/rancher/k3s/k3s.yaml
        regexp: '127.0.0.1'
        replace: '192.168.178.246'

    - name: Ensure K3s is running
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Get K3s token
      command: cat /var/lib/rancher/k3s/server/token
      register: k3s_token
      changed_when: false
